on:
  workflow_dispatch:
    inputs:
      tenant:
        description: 'Select Entra Tenant'
        required: true
        default: 'dev'
        type: choice
        options:
          - prod
          - dev
          - test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run deployment script
        shell: pwsh
        run: ./scripts/deploy.ps1 -Tenant "${{ github.event.inputs.tenant }}"
